notifications:
  email: false
matrix:
  include:

    #####################################################################
    # Job 1: CodeQuality
    #####################################################################
    - env: CodeQuality
      sudo: false
      language: php
      php: 7.1
      cache:
        directories:
          - vendor
          - bin
      before_install:
        - ./etc/travis-ci/disable-xdebug.sh
      install:
        - composer install --prefer-source
      script:
        - ./bin/phing check-codestandards
        - ./bin/phing phpstan
